// app
export const APP_TOGGLE_MOBILE_MENU = 'APP_TOGGLE_MOBILE_MENU'
export const APP_SET_RECAPTCHA_VALID = 'APP_SET_RECAPTCHA_VALID'
// Auth
export const LOGOUT = 'LOGOUT'

// Fields
export const FETCH_REQUEST = 'FETCH_REQUEST'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAILURE = 'FETCH_FAILURE'
export const FETCH_COMPLETE = 'FETCH_COMPLETE'

export const CALL_ACTION = 'CALL_ACTION'

export const SET_IN = 'SET_IN'
export const CHANGE_INPUT = 'CHANGE_INPUT'
export const CHANGE_CHECKBOX = 'CHANGE_CHECKBOX'

export const VALIDATE_INPUT = 'VALIDATE_INPUT'
export const VALIDATE_INPUT_BY_FLAG = 'VALIDATE_INPUT_BY_FLAG'

export const SELECT_COMBOBOX = 'SELECT_COMBOBOX'
export const SELECT_COMBOBOX_AND_ADD_TO_LIST = 'SELECT_COMBOBOX_AND_ADD_TO_LIST'

export const REMOVE_FROM_LIST_BY_INDEX = 'REMOVE_FROM_LIST_BY_INDEX'
export const REMOVE_FROM_LIST_BY_VALUE = 'REMOVE_FROM_LIST_BY_VALUE'
export const ADD_TO_LIST_WITH_TEMPLATE = 'ADD_TO_LIST_WITH_TEMPLATE'
export const ADD_TO_LIST = 'ADD_TO_LIST'
export const ADD_TO_LIST_UNIQUE = 'ADD_TO_LIST_UNIQUE'
export const CHANGE_LIST_ITEM = 'CHANGE_LIST_ITEM'

export const MAP_SET = 'MAP_SET'
export const MAP_REMOVE = 'MAP_REMOVE'
export const MAP_REMOVE_IN = 'MAP_REMOVE_IN'

export const PAGINATION_TO_BEGIN = 'PAGINATION_TO_BEGIN'
export const PAGINATION_TO_END = 'PAGINATION_TO_END'
export const PAGINATION_GO_NEXT = 'PAGINATION_GO_NEXT'
export const PAGINATION_GO_BACK = 'PAGINATION_GO_BACK'
